export default {
    DISPATCH: 'DISPATCH',
    SUBSCRIBE: 'SUBSCRIBE',
    UNSUBCRIBE: 'UNSUBCRIBE',
    SEND_COMPONENT_PROPS: 'SEND_COMPONENT_PROPS',
    SET_OPTIONS_REQUEST: 'SET_OPTIONS_REQUEST',
};
