export default {
    WORKER_IS_RESPONDING: 'WORKER_IS_RESPONDING',
    STATE_CHANGED: 'STATE_CHANGED',
    REQUEST_COMPONENT_PROPS: 'REQUEST_COMPONENT_PROPS',
    SET_OPTIONS_COMPLETE: 'SET_OPTIONS_COMPLETE',
};
