export default {
    EXECUTE_IN_WINDOW_REQUEST: 'EXECUTE_IN_WINDOW_REQUEST',
    EXECUTE_IN_WINDOW_SUCCESS: 'EXECUTE_IN_WINDOW_SUCCESS',
    EXECUTE_IN_WINDOW_FAILURE: 'EXECUTE_IN_WINDOW_FAILURE',
};
